version: "3.9"
services:
  webapp-beta:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GO_MAP_PORT=${GO_MAP_PORT}
    environment:
      - GIN_MODE=debug
      - IPINFO_TOKEN
      - GO_MAP_PORT=${GO_MAP_PORT}
    ports:
      - "${GO_MAP_PORT}:${GO_MAP_PORT}" # Different port to avoid conflicts
    volumes:
      - ./db:/app/db # Persist database changes
      - ./static:/app/static # Mount static files for live development
      - ./templates:/app/templates # Mount templates for live development
    restart: unless-stopped