version: "3.9"
services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Expose port 8080 on the host
    volumes:
      - ./db:/app/db # Persist database changes
      - ./static:/app/static # Mount static files for live development
      - ./templates:/app/templates # Mount templates for live development
    environment:
      - GIN_MODE=release # Optional: Production mode for Go 
    restart: unless-stopped

